server:
  port: ${CONFIG_SERVER_PORT} #8888
spring:
  security:
    user:
      name: ${CONFIG_SERVER_USER} #root
      password: ${CONFIG_SERVER_PASSWORD} #s3cr3t
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS}
  application:
    name: config-service

jasypt:
  encryptor:
    algorithm: ${JASYPT_ALGORITHM}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
