version: '3.9'
services:

###################### MYSQL #######################

#  keycloak:
#    image: 127.0.0.1:8082/jboss/keycloak
##    restart: always
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#      JAVA_OPTS: >
#        -Djgroups.bind_addr=127.0.0.1
#        -Dkeycloak.profile.feature.scripts=enabled
#        -Dkeycloak.profile.feature.upload_scripts=enabled
#      #        -Djgroups.bind_addr=`hostname -I`
#      DB_VENDOR: mariadb
#      DB_ADDR: localhost
#      DB_PORT: 3306
#      DB_DATABASE: service-gw
#      JDBC_PARAMS: '?useUnicode=true&characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8&createDatabaseIfNotExist=true'
#      DB_SCHEMA: service-gw
#      DB_USER: keycloak
#      DB_PASSWORD: password
#    network_mode: "host"

###################### ORACLE #######################

  keycloak-server:
    container_name: keycloak-service
    hostname: keycloak-server
    image: 127.0.0.1:8082/jboss/keycloak
#    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS: >
        -Djboss.http.port=8080
        -Djboss.management.http.port=9990
        -Djboss.management.https.port=9993
        -Djgroups.bind_addr=127.0.0.1
        -Dkeycloak.profile.feature.scripts=enabled
        -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: oracle
      DB_ADDR: maindb-19c.modernisc.com
#      DB_ADDR: 192.168.50.211
      DB_PORT: 1521
#      DB_DATABASE: abiskishdb
      DB_DATABASE: maindb
      DB_SCHEMA: gw_serivce
      DB_USER: gw_serivce
      DB_PASSWORD: gw_serivce
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      DEBUG: 'false'
      DEBUG_PORT: '*:5757'
    volumes:
      - "./jdbc:/opt/jboss/keycloak/modules/system/layers/base/com/oracle/jdbc/main/driver"
#    network_mode: "host"
    networks:
      spring-cloud-network:
        aliases:
          - keycloak-server
    ports:
      - 1521:1521
      - 8080:8080
      - 9990:9990
      - 9993:9993
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  spring-cloud-network:
    driver: bridge
    external: true