server:
 port: 8484
encrypt:
  #  key: pdr@102030 #symmetric key
  key-store:
    alias: config-server-key
    location: file://${user.dir}/server.jks
    #    location: classpath:/config-server.jks
    password: my-k34-s3cr3t
    secret: my-k34-s3cr3t
#logging:
#  file:
#    name: /home/parisa/IdeaProjects/microservice/elk/logstash*.log
